### ISSUE TITLE
Pouzivat misto enum jeji modernejsi c++ verzi

### ISSUE THREAD

**Issue by fan1x** [KatDan/GeoMapProjector#2]
https://github.com/KatDan/GeoMapProjector/blob/cb66b10d75f903f4d8c68445e8a6b6a2bd5f8a87/GeoMapProjector/include/coords.hpp#L15

**Comment by fan1x** [comment]
+ neni potreba pri predavani parametru psat znova `enum`, tohle se delalo v C, ale C++ to neni bezne (https://github.com/KatDan/GeoMapProjector/blob/cb66b10d75f903f4d8c68445e8a6b6a2bd5f8a87/GeoMapProjector/include/database.hpp#L32)

**Comment by KatDan** [comment]
enumy navyše odstránené.

**Comment by fan1x** [comment]
Neprijde mi? Napr: https://github.com/KatDan/GeoMapProjector/blob/ab966f254b164d24d1ccfaa035d6e97268b2e9ab/GeoMapProjector/include/database.hpp#L17
Myslel jsem nahrati pomoci `enum class`

**Comment by KatDan** [comment]
Aha, pardon, už som pochopila, čo mám opraviť :D opravené.
