### ISSUE TITLE
Odstranit warningy

### ISSUE THREAD

**Issue by fan1x** [KatDan/GeoMapProjector#3]
Nevim, co pouzivas za prekladac, ale zkus prosim zapnout warnings a kompilovat s nimi -> ja zkousel na GCC (https://stackoverflow.com/questions/2368811/how-to-set-warning-level-in-cmake) a naslo mi jich tam dost, tak je pls zkus odstranit :)

**Comment by KatDan** [comment]
malo by to byť vyriešené, všetky warningy boli len na unused parameter pri virtuálnych metódach.
