### ISSUE TITLE
Pouzit pure virtual metody

### ISSUE THREAD

**Issue by fan1x** [KatDan/GeoMapProjector#4]
Pokud chces, aby funkce byla virtualni, ale `base` class nemusi mit implementaci -> idealne udelat metodu pure virtual. 
Napriklad tohle: https://github.com/KatDan/GeoMapProjector/blob/cb66b10d75f903f4d8c68445e8a6b6a2bd5f8a87/GeoMapProjector/include/coords.hpp#L30

**Comment by KatDan** [comment]
virtuálne funkcie purified na `virtual double get_singleton_value() = 0;`
