### ISSUE TITLE
Vylepsit viditelnost atributu ve tride

### ISSUE THREAD

**Issue by fan1x** [KatDan/GeoMapProjector#5]
Neni vzdy potreba, aby vsechny atributy ve tride byly `public`, kazi to potom OOP. 
napriklad tady: https://github.com/KatDan/GeoMapProjector/blob/cb66b10d75f903f4d8c68445e8a6b6a2bd5f8a87/GeoMapProjector/include/database.hpp#L85

**Comment by KatDan** [comment]
atribúty v `Controller` som rozdelila na private a public, so všetkými atribútmi v `Database` však pracujú funkcie z iných tried. Podobná situácia je aj v ostatných triedach, takže sa mi podarilo urobiť private jedine veci v `Controller`.
