### ISSUE TITLE
Muzes pouzit raw string literal

### ISSUE THREAD

**Issue by fan1x** [KatDan/GeoMapProjector#7]
https://github.com/KatDan/GeoMapProjector/blob/cb66b10d75f903f4d8c68445e8a6b6a2bd5f8a87/GeoMapProjector/src/controller.cpp#L62
Na tohle lze klidne pouzit `raw string literal`: https://en.cppreference.com/w/cpp/language/string_literal

**Comment by fan1x** [comment]
+ tohleto by urcite mely byt constanty

**Comment by KatDan** [comment]
raw string literal je cool
