### ISSUE TITLE
Pokud funkce nepristupuji k vnitrnostem tridy, mohou byt static

### ISSUE THREAD

**Issue by fan1x** [KatDan/GeoMapProjector#8]
napriklad: https://github.com/KatDan/GeoMapProjector/blob/cb66b10d75f903f4d8c68445e8a6b6a2bd5f8a87/GeoMapProjector/src/controller.cpp#L202

**Comment by KatDan** [comment]
`help_cmd()` pristupuje k stringom, ktoré sú súčasťou triedy, takže myslím nemôže byť static.
